language: scala
scala:
  - 2.12.8
jdk: oraclejdk11

sudo: false

script:
  - sbt coverage test assembly

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

notifications:
  webhooks:
    urls:
      - https://hooks.eciavatta.it/hooks/scalacraft-deploy
